version: "3.3"
services:
    logging_service:
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - type: bind
              source: ./src/Host/appsettings.Production.json
              target: /app/appsettings.Production.json
        ports:
            - "5002:5002"